# Generated by Django 6.0 on 2025-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
    ]
