# Generated by Django 6.0 on 2025-12-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0003_patientprofile_medical_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='skin_type',
            field=models.CharField(blank=True, choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20, null=True),
        ),
    ]
