# Generated by Django 6.0 on 2025-12-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0004_alter_patientprofile_skin_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=200)),
                ('treatment_plan', models.TextField()),
                ('prescription', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='avicenna_ap_doctor__e7ad36_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='avicenna_ap_patient_d78756_idx',
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='pain_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='status',
            field=models.CharField(choices=[('analyzed', 'Analyzed'), ('review', 'Under Review'), ('reviewed', 'Reviewed')], default='review', max_length=20),
        ),
        migrations.AddField(
            model_name='submissionreport',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='avicenna_api.skinanalysis'),
        ),
        migrations.AddField(
            model_name='submissionreport',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
