# Generated by Django 6.0 on 2025-12-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0005_submissionreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionreport',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='submissionreport',
            name='doctor',
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['doctor', 'created_at'], name='avicenna_ap_doctor__e7ad36_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['patient', 'created_at'], name='avicenna_ap_patient_d78756_idx'),
        ),
        migrations.DeleteModel(
            name='SubmissionReport',
        ),
    ]
