# Generated by Django 6.0 on 2025-12-20 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0006_remove_submissionreport_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='pain_level',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='place',
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='skin_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='avicenna_api.skinanalysis'),
        ),
    ]
