# Generated by Django 6.0 on 2025-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0007_remove_submission_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinanalysis',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
