# Generated by Django 6.0 on 2026-03-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avicenna_api.submission'),
        ),
    ]
