# Generated by Django 6.0 on 2026-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avicenna_api', '0012_medicalauditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='avicenna_ap_doctor__e7ad36_idx',
        ),
        migrations.RemoveIndex(
            model_name='submission',
            name='avicenna_ap_patient_d78756_idx',
        ),
        migrations.AddField(
            model_name='skinanalysis',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('analyzed', 'Analyzed'), ('review', 'Under Review'), ('reviewed', 'Reviewed'), ('failed', 'Failed')], default='review', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['patient', '-created_at'], name='avicenna_ap_patient_b2f1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcase',
            index=models.Index(fields=['patient', 'is_active'], name='avicenna_ap_patient_82fa31_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='avicenna_ap_user_id_ff1c94_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='avicenna_ap_user_id_e82aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['patient', '-created_at'], name='avicenna_ap_patient_b4ba33_idx'),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['medical_case', 'created_at'], name='avicenna_ap_medical_4595ef_idx'),
        ),
        migrations.AddIndex(
            model_name='skinanalysis',
            index=models.Index(fields=['status'], name='avicenna_ap_status_45f88b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['doctor', '-created_at'], name='avicenna_ap_doctor__ce0e14_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['patient', '-updated_at'], name='avicenna_ap_patient_09c543_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['doctor', 'status'], name='avicenna_ap_doctor__192b05_idx'),
        ),
    ]
