# Generated by Django 6.0 on 2025-12-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skinphoto',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='skinphoto',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinphoto',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='skinphoto',
            name='raw_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinphoto',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skinphoto',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
